"""
CLAUDE.md generator for EriRPG.

Creates project-specific CLAUDE.md files that replace SuperClaude's
static system prompts with dynamic, project-aware context.

SuperClaude: One static CLAUDE.md with ~20k tokens of generic instructions.
EriRPG: Dynamic CLAUDE.md with ~2-3k tokens of project-specific knowledge.

Usage:
    eri-rpg context                    # Print to stdout
    eri-rpg context --write            # Write to ./CLAUDE.md
    eri-rpg context --stage implement  # Set workflow stage
    eri-rpg context --persona critic   # Override persona
"""

from pathlib import Path
from typing import Optional, List
from datetime import datetime

from .session_context import (
    build_context,
    SessionContext,
    context_from_knowledge_store,
)
from .workflow import Stage, get_persona_for_stage
from .persona import Persona


def generate_claude_md(
    project_path: str,
    project_name: str,
    description: str = "",
    patterns: List[str] = None,
    decisions: List[str] = None,
    key_modules: List[str] = None,
    current_task: str = None,
    must_haves: List[str] = None,
    roadmap: str = None,
    stage: Stage = Stage.IDLE,
    persona: Persona = None,
    compact: bool = False,
) -> str:
    """
    Generate CLAUDE.md content for a project.

    This is called by `eri-rpg context` and can be piped to CLAUDE.md
    or used directly in prompts.

    Args:
        project_path: Path to project root
        project_name: Display name for project
        description: Project description
        patterns: List of learned patterns
        decisions: List of decisions made
        key_modules: List of important module paths
        current_task: Current task description
        must_haves: List of must-have criteria
        roadmap: Roadmap summary
        stage: Current workflow stage
        persona: Persona override (or None for stage default)
        compact: Minimize token usage

    Returns:
        CLAUDE.md content as string
    """
    # Default persona from stage if not specified
    if persona is None:
        persona = get_persona_for_stage(stage)

    ctx = SessionContext(
        project_name=project_name,
        project_path=project_path,
        project_description=description,
        stage=stage,
        persona=persona,
        persona_override=(persona is not None),
        learned_patterns=patterns or [],
        recent_decisions=decisions or [],
        key_modules=key_modules or [],
        current_task=current_task,
        must_haves=must_haves or [],
        roadmap_summary=roadmap,
    )

    content = build_context(ctx, compact=compact)

    # Add generation metadata (helps with debugging)
    content += f"""
---
*Generated by EriRPG {_get_version()} at {datetime.now().strftime('%Y-%m-%d %H:%M')}*
"""

    return content


def generate_claude_md_from_store(
    project_path: str,
    project_name: str,
    stage: Stage = Stage.IDLE,
    persona: Persona = None,
    current_task: str = None,
    compact: bool = False,
) -> str:
    """
    Generate CLAUDE.md from existing knowledge store.

    Loads patterns, decisions, and learnings from .eri-rpg/knowledge.json
    and builds context automatically.

    Args:
        project_path: Path to project root
        project_name: Project name
        stage: Current workflow stage
        persona: Persona override
        current_task: Current task description
        compact: Minimize token usage

    Returns:
        CLAUDE.md content as string
    """
    ctx = context_from_knowledge_store(
        project_path=project_path,
        project_name=project_name,
        stage=stage,
        persona=persona,
        current_task=current_task,
    )

    content = build_context(ctx, compact=compact)

    content += f"""
---
*Generated by EriRPG {_get_version()} at {datetime.now().strftime('%Y-%m-%d %H:%M')}*
*Knowledge: {len(ctx.learned_patterns)} patterns, {len(ctx.recent_decisions)} decisions*
"""

    return content


def write_claude_md(project_path: str, content: str) -> Path:
    """
    Write CLAUDE.md to project directory.

    Args:
        project_path: Path to project root
        content: CLAUDE.md content

    Returns:
        Path to written file
    """
    path = Path(project_path) / "CLAUDE.md"
    path.write_text(content)
    return path


def update_claude_md(
    project_path: str,
    project_name: str,
    stage: Stage = None,
    persona: Persona = None,
    current_task: str = None,
) -> Path:
    """
    Update CLAUDE.md from current knowledge store.

    Convenience function that loads knowledge and writes CLAUDE.md.

    Args:
        project_path: Path to project root
        project_name: Project name
        stage: Workflow stage (default: IDLE)
        persona: Persona override
        current_task: Current task

    Returns:
        Path to written CLAUDE.md
    """
    content = generate_claude_md_from_store(
        project_path=project_path,
        project_name=project_name,
        stage=stage or Stage.IDLE,
        persona=persona,
        current_task=current_task,
    )

    return write_claude_md(project_path, content)


def _get_version() -> str:
    """Get EriRPG version."""
    try:
        from . import __version__
        return __version__
    except ImportError:
        return "0.55.0-alpha"


# Template for projects without knowledge store
MINIMAL_TEMPLATE = """# {project_name}

## EriRPG Project

This project is managed by EriRPG. Run `eri-rpg sync --learn` to populate
the knowledge base, then `eri-rpg context --write` to generate full context.

## Quick Commands

```
/analyze    - Understand codebase structure
/discuss    - Plan approach and roadmap
/implement  - Write code to spec
/review     - Critique and find issues
/debug      - Investigate problems
```

## Personas

```
/architect  - Systems thinking, tradeoffs
/dev        - Pragmatic, ship it
/critic     - Find issues, security
/analyst    - Root cause, debugging
/mentor     - Explain, teach
```

---
*Generated by EriRPG*
"""


def generate_minimal_claude_md(project_name: str) -> str:
    """Generate minimal CLAUDE.md for projects without knowledge."""
    return MINIMAL_TEMPLATE.format(project_name=project_name)
